spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.170.128/recsys?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jackson:
    default-property-inclusion: non_null  #使返回的Json数据不包含null值
  redis:
    host: 192.168.170.128
    port: 6379
  main:
    allow-bean-definition-overriding: true

server:
  servlet:
    context-path: /recsys
logging:
  level:
    com.sky.dataobject.mapper.ProductCategoryMapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml
